scielo_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('stylechecker.urls', namespace='stylechecker')),
    path('admin/', admin.site.urls),
]

stylechecker/urls.py
from django.urls import path

from .views import XMLValidateView


app_name = 'stylechecker'
urlpatterns = [
    path('', XMLValidateView.as_view(), name='xml-validator')
]

stylechecker/models.py
import os

from django.db import models
from django.conf import settings
from packtools.utils import config_xml_catalog
from packtools import stylechecker


class XMLFileValidator:

    def __init__(self, uploaded_file):
        self.uploaded_file = uploaded_file

    def _generate_html_result(self):
        self.result_xml_name = os.path.join(
            settings.MEDIA_ROOT,
            'result_{}'.format(self.uploaded_file.name)
        )
        with open(self.result_xml_name, 'w+b') as fb:
            stylechecker.annotate(self.xml_validator, fb)

    def _create_sps_errors_object(self, xml_result, errors):
        style_errors_object = [{
            error['message']: [
                self._parse_sps_error_detail(xml_result, index)
                for index, line in enumerate(xml_result)
                if error['message'] in line
            ]
            for error in errors
        }]
        return style_errors_object

    def _parse_sps_error_detail(self, xml_result, error_line):
        start_line = error_line - 3 if error_line >= 3 else 0
        end_line = -1 if error_line >= len(xml_result) else error_line + 3
        xml_result_lines = xml_result[start_line:end_line]
        return {
            'apparent_line': error_line,
            'doc_slice': ''.join(xml_result_lines)
        }

    def classify_errors(self):
        summary = stylechecker.summarize(self.xml_validator)
        classified_errors = {
            'dtd_errors': [item for item in summary['dtd_errors']]
        } if summary['dtd_errors'] else {}

        self._generate_html_result()
        xml_result = None
        with open(self.result_xml_name, 'r') as xml:
            xml_result = [line for line in xml]

        classified_errors.update({
            'style_errors': self._create_sps_errors_object(xml_result, errors)
            for _, errors in summary['style_errors'].items()
        })
        return classified_errors

    @config_xml_catalog
    def validate_handler(self):
        self.xml_validator = stylechecker.get_xmlvalidator(
            xmlpath=self.uploaded_file,
            no_network=True,
            extra_sch=[]
        )
        is_valid, _ = self.xml_validator.validate_all()
        return is_valid

stylechecker/forms.py
from django import forms


class UploadXMLFileForm(forms.Form):
    file = forms.FileField(allow_empty_file=False)

stylechecker/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView

from .forms import UploadXMLFileForm
from .models import XMLFileValidator


class XMLValidateView(FormView):
    form_class = UploadXMLFileForm
    template_name = 'index.html'

    def post(self, request, *args, **kwargs):
        form = UploadXMLFileForm(request.POST, request.FILES)
        if form.is_valid():
            context = {'form': form}
            xml_file_validator = XMLFileValidator(request.FILES['file'])
            if not xml_file_validator.validate_handler():
                classified_errors = xml_file_validator.classify_errors()
                context.update({'summary': classified_errors})
            return render(
                request,
                context=context,
                template_name=self.template_name
            )

stylechecker/templates/file_form.html
<form enctype="multipart/form-data"
      method="post"
      action="{% url 'stylechecker:xml-validator' %}">
    {% csrf_token %}
    <div class="input-group">
        <div class="custom-file">
            <input type="file"
                   class="custom-file-input"
                   id="customFile"
                   value="{{ form.file }}">
            <label class="custom-file-label"
                   for="customFile">
                Selecione o arquivo XML
            </label>
        </div>
        <div class="input-group-append">
            <button id="btn-file-upload" type="submit" class="btn btn-secondary">
                Validar
            </button>
        </div>
    </div>
</form>

stylechecker/templates/result_error.html
<div class="card">
     <div class="card-header"
          id="line{{ msg_number }}{{ forloop.counter }}">
         <p class="mb-0">
             <button class="btn btn-link collapsed"
                     data-toggle="collapse"
                     data-target="#collapse_line{{ msg_number }}{{ forloop.counter }}"
                     aria-controls="collapse_line{{ msg_number }}{{ forloop.counter }}">
                 Line {{ line_number }}
             </button>
         </p>
     </div>
     <div id="collapse_line{{ msg_number }}{{ forloop.counter }}"
          class="collapse"
          aria-labelledby="line{{ msg_number }}{{ forloop.counter }}"
          data-parent="#accordion_error_{{ msg_number }}{{ forloop.counter }}">
         <div class="card-body">
             <div class="row no-gutters">
                 <div class="col-1">
                     <br><br><br>
                     <samp>
                         L{{ line.apparent_line }}-->
                     </samp>
                 </div>
                 <div class="col col-11">
                     <pre lang="xml" class="pre-scrollable">
                         {{ error }}
                     </pre>
                 </div>
             </div>
         </div>
     </div>
</div>

stylechecker/templates/result_errors.html
<div class="card">
     <div class="card-header bg-info"
          id="heading{{ forloop.counter }}">
         <h5 class="mb-0">
             <span class="badge badge-secondary">
                 {{ level }}
             </span>
             <button class="btn btn-link text-white collapsed"
                     data-toggle="collapse"
                     data-target="#collapse_heading{{ forloop.counter }}"
                     aria-controls="collapse_heading{{ forloop.counter }}">
                 {{ message }}
             </button>
             <span class="badge badge-pill badge-warning">
                 {{ lines|length }} Ocorrênci{{ lines|length|pluralize:"a,as" }}
             </span>
         </h5>
     </div>
     <div id="collapse_heading{{ forloop.counter }}"
          class="collapse"
          aria-labelledby="heading{{ forloop.counter }}"
          data-parent="#accordion_summary">
         <div class="card-body">
             {% for line in lines %}
                 {% if lines|length > 1 %}
                 <div id="accordion_error_{{ msg_number }}{{ forloop.counter }}">
                     {% include 'result_error.html' with line_number=line.apparent_line error=line.doc_slice %}
                 </div>
                 {% else %}
                 <div class="row no-gutters">
                     <div class="col-1">
                         <br><br><br>
                         <samp>
                             L{{ line.apparent_line }}-->
                         </samp>
                     </div>
                     <div class="col col-11">
                         <pre lang="xml" class="pre-scrollable">
                             {{ line.doc_slice }}
                         </pre>
                     </div>
                 </div>
                 {% endif %}
             {% endfor %}
         </div>
     </div>
</div>

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>SciELO</title>
  </head>
  <body>
    {% include 'base/header.html' %}

    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block js %}{% endblock %}
  </body>
</html>

templates/base/header.html
{% url 'home' as home_url %}

<div class="jumbotron jumbotron-fluid bg-info">
    <div class="container">
        <h1 class="display-3 text-center text-white">SciELO Style Checker</h1>
        <br />
        <h4 class="lead text-center text-white">
            Ferramenta para verificar conformidade de arquivos XML com o Estilo SciELO*
        </h4>
        <br />
    </div>
</div>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="header" class="row">
    <div class="mx-auto p-5">
        {% include 'file_form.html' %}
    </div>
</div>
{% if form.is_valid %}
<div id="result" class="container-fluid">
    <div class="row">
        <h2>Resultado</h2>
    </div>
    <div class="row pb-5">
        <div id="accordion_summary"
             class="container-fluid">
            {% for errors_level, errors_list in summary.items %}
                {% for errors in errors_list %}
                    {% for message, error_lines in errors.items %}
                        {% with msg_number=forloop.counter %}
                        {% include 'result_errors.html' with level=errors_level lines=error_lines %}
                        {% endwith %}
                    {% endfor %}
                {% endfor %}
            {% empty %}
                <div class="alert alert-success" role="alert">
                    Documento validado sem erros
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}
{% block js %}
    <script>
    $(function () {
        $("#customFile").change(function () {
          var filename = $(this).val();
          var fieldlabel = $(this).next('.custom-file-label');
          fieldlabel.html(filename.replace("C:\\fakepath\\", ""));
        });
    });
    </script>
{% endblock %}